### ISSUE TITLE
貌似签名的时候timestamp使用的是毫秒数

### ISSUE THREAD

**Issue by KingMario** [rongcloud/server-sdk-nodejs#11]
官方文档里timestamp说的是秒数
但从代码里看，貌似timestamp使用的是毫秒数，目前看调用没有问题。
但以后不知道服务器会不会严格起来，如果差几秒就算了，如果差1000倍就认为签名不正确？
或者是官方文档写错了？

**Comment by crystaldust** [comment]
@KingMario 感谢提醒，以官方文档为准，已经更新为秒数，npm的版本是1.0.3
