### ISSUE TITLE
Parse response text when possible

### ISSUE THREAD

**Issue by bcho** [rongcloud/server-sdk-nodejs#14]
Can we parse rongcloud's response text as json/xml when possible? This can help to reduce the boilerplate code.

In order to keep the api's backwards compatibility, we can add a parameter after `format` call `parse`, which is defaults to `false`, for example:

``` js
rongcloudSDK.user.getToken(userId, username, avatar, 'json', true, callback);
```

 Or we can add a global control setting to make it work:

``` json
rongcloudSDK.setParseResponse(true);
```

**Comment by crystaldust** [comment]
Yeah, to keep the code clear, the latter way is better, feel free to make pull request~

**Comment by yuhongda0315** [comment]
The SDK 3.0.0 has fixed this problem
