### ISSUE TITLE
HTTPS证书错误

### ISSUE THREAD

**Issue by tdzl2003** [rongcloud/server-sdk-nodejs#21]
Error: Hostname/IP doesn't match certificate's altnames: "Host: api.cn.rong.io. is not in the cert's altnames: DNS:*.cn.ronghub.com"

从文档上看，请求的地址是api.cn.ronghub.com，而npm上的版本是 api.cn.rong.io。

我注意到github上的版本已经更新了，是否npm上的版本还未更新？

**Comment by ericyangpan** [comment]
先暂时引用 git+https://github.com/rongcloud/server-sdk-nodejs.git 吧。

**Comment by yuhongda0315** [comment]
SDK 已发布 3.0.0 版本，NPM、GitHub 同步更新，3.0.0 版本 SDK API 不再向老版本兼容，老版本 SDK 可用但不再维护
