### ISSUE TITLE
rongcloudSDK.chatroom.create方法与server api有出入

### ISSUE THREAD

**Issue by xiongxiong109** [rongcloud/server-sdk-nodejs#22]
官方文档指定`/chatroom/create`方法，传递的参数是String类型的表单参数

``` js
chatroom[id]=name
```

但是在您的sdk中封装的 `/lib/chatroom.js`中，传递的参数`chatRoomIDNamePairs`为json数组，这一点没有说清楚，所以在调试的时候发现了这个问题。

**Comment by yuhongda0315** [comment]
由于支持多聊天室，所以以数组方式传入，接口内部会自动转为 String

SDK 3.0.0 已发布，如需使用，建议升级，老版本 SDK 可用但不再维护
