### ISSUE TITLE
怎么让请求阻塞 ，，

### ISSUE THREAD

**Issue by kmp6781** [rongcloud/server-sdk-nodejs#24]
新手见谅，  调用接口然后callback里的代码都同步执行了，然后调试一圈代码到 agent.end 就执行我自己的代码先了，，然后再是回到 agent.end里 

我想实现先return callback  然后再操作我自己的后续代码该怎么改呢

**Comment by yuhongda0315** [comment]
非常抱歉，没有及时回复

1、没有理解您想做什么？可以先详细描述业务场景，没有上下文，无法给出准确回答的

2、建议不要直接修改 SDK 源码，会影响日后 SDK 升级，有问题可提 Issue 讨论或提交 PR

**Comment by shuise** [comment]
与其他服务器端语言相比，node 最大的特色+优势就是不阻塞，你需要转变思路，不要用其他语言的思路玩 node。
