### ISSUE TITLE
Message.private.publish 方法缺少参数

### ISSUE THREAD

**Issue by Harbon** [rongcloud/server-sdk-nodejs#25]
参数个数和官方文档有出入，比如缺少 isIncludeSender

**Comment by yuhongda0315** [comment]
很抱歉没有及时回复，目前已发布 3.0 版本 SDK，老版本 SDK 可用但不再维护，后续使用请升级，升级前请参考 [REAMD.md](https://github.com/rongcloud/server-sdk-nodejs/)
