### ISSUE TITLE
客户端请求服务端获取Token不在SDK？

### ISSUE THREAD

**Issue by ilaipi** [rongcloud/server-sdk-nodejs#26]
[web 端怎么获取 token？](https://support.rongcloud.cn/kb/NDU0)

看这个页面上说，

> 请务必确保在服务端换取 Token

但是在sdk的文档中看不到怎么获取Token

**Comment by yuhongda0315** [comment]
SDK 中获取 Token 接口为 User.register：

文档：https://www.rongcloud.cn/docs/server_sdk_api/user/user.html#register

示例：https://github.com/rongcloud/server-sdk-nodejs/blob/master/example/promise/user/user.js

**Comment by ilaipi** [comment]
好的吧
