### ISSUE TITLE
OnlineStatus.check()方法未定义

### ISSUE THREAD

**Issue by ywb1005** [rongcloud/server-sdk-nodejs#30]
![image](https://user-images.githubusercontent.com/9530964/70707654-96cfb400-1d13-11ea-893f-35dce0afd7bc.png)
文档中有一个用户状态查询的方法，实际调用中该方法未定义
`var appkey = '';
// 替换成您自己的 Secret
var secret = '';

var RongSDK = require('rongcloud-sdk')({
    appkey: appkey,
    secret: secret
});
RongSDK.User.OnlineStatus.check({id:'123'}).then(res => {console.log(res)}).catch(err => {console.log(err)})`

**Comment by YongHao0** [comment]
此问题已于 2020-01-05 修复. 请下载最新版
